---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/criatura/
    - /bin/cp -r * $DEPLOYPATH/bando-app #copy all from root
    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/bando
    - /bin/cp ./public/js/*.js $DEPLOYPATH/public_html/bando/js
    - /bin/cp ./public/css/*.css $DEPLOYPATH/public_html/bando/css